name: campus_gigs_income_tracker
description: A Flutter app for student jobs and income tracking with premium access.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_analytics: ^11.5.2
  firebase_messaging: ^15.2.9

  # Google Sign-In
  google_sign_in: ^6.1.0

  # In-app purchases
  in_app_purchase: ^3.2.0

  # Ads
  google_mobile_ads: ^6.0.0

  # UI & Utils
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  table_calendar: ^3.0.9
  image_picker: ^1.0.7
  firebase_storage: ^12.4.9
  fl_chart: ^1.0.0
  csv: ^5.1.1
  path_provider: ^2.1.2
  pdf: ^3.10.8
  printing: ^5.12.0
  intl: ^0.20.2
  url_launcher: ^6.2.6
  file_picker: ^10.2.0
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_logo.svg
    - assets/images/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
