name: edumanage
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.1
  firebase_crashlytics: ^4.3.8
  connectivity_plus: ^6.0.3
  google_sign_in: ^6.2.1
  js: ^0.7.1
  # Freemium model dependencies
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
